[2023-09-29T06:51:34.431+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ourfirst_dag.first_task manual__2023-09-29T06:43:30.119459+00:00 [queued]>
[2023-09-29T06:51:34.435+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ourfirst_dag.first_task manual__2023-09-29T06:43:30.119459+00:00 [queued]>
[2023-09-29T06:51:34.435+0000] {taskinstance.py:1359} INFO - Starting attempt 5 of 6
[2023-09-29T06:51:34.441+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): first_task> on 2023-09-29 06:43:30.119459+00:00
[2023-09-29T06:51:34.444+0000] {standard_task_runner.py:57} INFO - Started process 1067 to run task
[2023-09-29T06:51:34.447+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ourfirst_dag', 'first_task', 'manual__2023-09-29T06:43:30.119459+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp7fl7azwt']
[2023-09-29T06:51:34.449+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask first_task
[2023-09-29T06:51:34.478+0000] {task_command.py:415} INFO - Running <TaskInstance: ourfirst_dag.first_task manual__2023-09-29T06:43:30.119459+00:00 [running]> on host 5a4c0e849059
[2023-09-29T06:51:34.520+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rachang' AIRFLOW_CTX_DAG_ID='ourfirst_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T06:43:30.119459+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-29T06:43:30.119459+00:00'
[2023-09-29T06:51:34.521+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-29T06:51:34.522+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/bash1.sh ']
[2023-09-29T06:51:34.528+0000] {subprocess.py:86} INFO - Output:
[2023-09-29T06:51:34.530+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /bash1.sh: No such file or directory
[2023-09-29T06:51:34.530+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-09-29T06:51:34.537+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-09-29T06:51:34.539+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ourfirst_dag, task_id=first_task, execution_date=20230929T064330, start_date=20230929T065134, end_date=20230929T065134
[2023-09-29T06:51:34.544+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 1067)
[2023-09-29T06:51:34.583+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-29T06:51:34.593+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
