[2023-09-29T11:13:32.614+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ourfirst_dag.create_postgres_table manual__2023-09-29T11:09:25.521763+00:00 [queued]>
[2023-09-29T11:13:32.618+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ourfirst_dag.create_postgres_table manual__2023-09-29T11:09:25.521763+00:00 [queued]>
[2023-09-29T11:13:32.618+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 6
[2023-09-29T11:13:32.624+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-09-29 11:09:25.521763+00:00
[2023-09-29T11:13:32.627+0000] {standard_task_runner.py:57} INFO - Started process 5038 to run task
[2023-09-29T11:13:32.630+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ourfirst_dag', 'create_postgres_table', 'manual__2023-09-29T11:09:25.521763+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpj35_lbl1']
[2023-09-29T11:13:32.632+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask create_postgres_table
[2023-09-29T11:13:32.662+0000] {task_command.py:415} INFO - Running <TaskInstance: ourfirst_dag.create_postgres_table manual__2023-09-29T11:09:25.521763+00:00 [running]> on host d55fc6ddd7e6
[2023-09-29T11:13:32.705+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rachang' AIRFLOW_CTX_DAG_ID='ourfirst_dag' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T11:09:25.521763+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-29T11:09:25.521763+00:00'
[2023-09-29T11:13:32.706+0000] {sql.py:274} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS dag_runs(
            de date,
            dag_id character varying,
            primary key (dt, dag_id)
            )
        
[2023-09-29T11:13:32.713+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-29T11:13:32.719+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-09-29T11:13:32.725+0000] {sql.py:418} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS dag_runs(
            de date,
            dag_id character varying,
            primary key (dt, dag_id)
            )
        , parameters: None
[2023-09-29T11:13:32.727+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "dt" named in key does not exist
LINE 5:             primary key (dt, dag_id)
                    ^

[2023-09-29T11:13:32.733+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ourfirst_dag, task_id=create_postgres_table, execution_date=20230929T110925, start_date=20230929T111332, end_date=20230929T111332
[2023-09-29T11:13:32.739+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 21 for task create_postgres_table (column "dt" named in key does not exist
LINE 5:             primary key (dt, dag_id)
                    ^
; 5038)
[2023-09-29T11:13:32.762+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-29T11:13:32.773+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
