[2023-09-29T06:56:38.571+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ourfirst_dag.first_task manual__2023-09-29T06:56:37.257777+00:00 [queued]>
[2023-09-29T06:56:38.575+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ourfirst_dag.first_task manual__2023-09-29T06:56:37.257777+00:00 [queued]>
[2023-09-29T06:56:38.576+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2023-09-29T06:56:38.582+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): first_task> on 2023-09-29 06:56:37.257777+00:00
[2023-09-29T06:56:38.585+0000] {standard_task_runner.py:57} INFO - Started process 194 to run task
[2023-09-29T06:56:38.587+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ourfirst_dag', 'first_task', 'manual__2023-09-29T06:56:37.257777+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpptw1fkbj']
[2023-09-29T06:56:38.589+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask first_task
[2023-09-29T06:56:38.618+0000] {task_command.py:415} INFO - Running <TaskInstance: ourfirst_dag.first_task manual__2023-09-29T06:56:37.257777+00:00 [running]> on host e347a9e9e6ab
[2023-09-29T06:56:38.660+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rachang' AIRFLOW_CTX_DAG_ID='ourfirst_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T06:56:37.257777+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-29T06:56:37.257777+00:00'
[2023-09-29T06:56:38.662+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-29T06:56:38.662+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/bash1.sh ']
[2023-09-29T06:56:38.668+0000] {subprocess.py:86} INFO - Output:
[2023-09-29T06:56:38.670+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /bash1.sh: No such file or directory
[2023-09-29T06:56:38.670+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-09-29T06:56:38.677+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-09-29T06:56:38.679+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ourfirst_dag, task_id=first_task, execution_date=20230929T065637, start_date=20230929T065638, end_date=20230929T065638
[2023-09-29T06:56:38.685+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 194)
[2023-09-29T06:56:38.722+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-29T06:56:38.732+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
