[2023-09-29T07:03:36.298+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ourfirst_dag.first_task manual__2023-09-29T07:03:35.173422+00:00 [queued]>
[2023-09-29T07:03:36.302+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ourfirst_dag.first_task manual__2023-09-29T07:03:35.173422+00:00 [queued]>
[2023-09-29T07:03:36.302+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2023-09-29T07:03:36.308+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): first_task> on 2023-09-29 07:03:35.173422+00:00
[2023-09-29T07:03:36.311+0000] {standard_task_runner.py:57} INFO - Started process 199 to run task
[2023-09-29T07:03:36.313+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ourfirst_dag', 'first_task', 'manual__2023-09-29T07:03:35.173422+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpcivc26vn']
[2023-09-29T07:03:36.315+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask first_task
[2023-09-29T07:03:36.344+0000] {task_command.py:415} INFO - Running <TaskInstance: ourfirst_dag.first_task manual__2023-09-29T07:03:35.173422+00:00 [running]> on host 419e399dc2c6
[2023-09-29T07:03:36.387+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rachang' AIRFLOW_CTX_DAG_ID='ourfirst_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T07:03:35.173422+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-29T07:03:35.173422+00:00'
[2023-09-29T07:03:36.388+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-29T07:03:36.389+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/scripts ']
[2023-09-29T07:03:36.395+0000] {subprocess.py:86} INFO - Output:
[2023-09-29T07:03:36.397+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /opt/***/scripts: Is a directory
[2023-09-29T07:03:36.398+0000] {subprocess.py:97} INFO - Command exited with return code 126
[2023-09-29T07:03:36.405+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2023-09-29T07:03:36.407+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ourfirst_dag, task_id=first_task, execution_date=20230929T070335, start_date=20230929T070336, end_date=20230929T070336
[2023-09-29T07:03:36.413+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task first_task (Bash command failed. The command returned a non-zero exit code 126.; 199)
[2023-09-29T07:03:36.446+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-29T07:03:36.456+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
